version: "3.7"
services:
  map-point:
    container_name: map-point
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - ".:/var/www/html/"
      - "./container/php/php.ini:/usr/local/etc/php/php.ini"
      # - "./container/php/pcov.ini:/usr/local/etc/php/conf.d/docker-php-ext-pcov.ini"
      - "./container/php/xdebug-local.ini:/usr/local/etc/php/conf.d/xdebug-local.ini"
      - "./container/apache2/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    ports:
      - "84:80"
    user: www-data
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "laravel-test.local:127.0.0.1"
